---
- name: "Prepare task variables"
  ansible.builtin.set_fact:
    paperless_ai_service_id: "paperless-ai"
    paperless_ai_docker_settings: "{{ paperless_ai_docker_settings_default | combine(paperless_ai_docker_settings) }}"

- name: "Make sure config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"
    mode: "0774"
  loop:
    - "{{ paperless_ai_install_dir }}/data"

- name: "Ensure {{ paperless_ai_docker_settings.network }} network exists"
  when: paperless_ai_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ paperless_ai_docker_settings.network }}"
    state: "present"

- name: "Run app container"
  community.general.docker_container:
    name: "{{ paperless_ai_service_id }}"
    image: "clusterzx/paperless-ai:{{ paperless_ai_version }}"
    networks:
      - name: "{{ paperless_ai_docker_settings.network }}"
    state: "started"
    env: "{{ paperless_ai_env_default | combine(paperless_ai_env) }}"
    ports:
      - "{{ paperless_ai_port }}:3000"
    volumes:
      - "{{ paperless_ai_install_dir }}/data:/app/data"
    restart_policy: "unless-stopped"
