# https://hay-kot.github.io/homebox/quick-start/#env-variables-configuration
---

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    homebox_service_id: "homebox"
    homebox_docker_settings: "{{ homebox_docker_settings_default | combine(homebox_docker_settings) }}"

- name: "Make sure {{ homebox_docker_settings.network }} docker network exists"
  when: homebox_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ homebox_docker_settings.network }}"
    state: "present"

- name: "Run homebox container"
  community.general.docker_container:
    name: "{{ homebox_service_id }}"
    image: "ghcr.io/sysadminsmedia/homebox:{{ homebox_version }}"
    networks:
      - name: "{{ homebox_docker_settings.network }}"
    state: "started"
    env: "{{ homebox_env_default | combine(homebox_env) }}"
    ports:
      - "{{ homebox_webui_port }}:7745"
    volumes:
      - "{{ homebox_install_dir }}:/data"
    restart_policy: "unless-stopped"
