---
- name: "Combine docker_settings with default docker_settings_default"
  ansible.builtin.set_fact:
    rss_docker_settings: "{{ rss_docker_settings_default | combine(rss_docker_settings) }}"

- name: "Make sure {{ rss_docker_settings.network }} docker network exists"
  when: rss_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ rss_docker_settings.network }}"
    state: "present"
    driver_options:
      # Limits docker interface MTU to fit Wireguard MTU https://stackoverflow.com/a/75868444
      #
      # TODO: Find a way to set this with _docker_settings variables, for all roles in the collection.
      # For bridge networks, /etc/docker/daemon.json is not an option: https://mlohr.com/docker-mtu
      com.docker.network.driver.mtu: 1420

- name: "Install RSSBridge"
  ansible.builtin.include_tasks: "rssbridge.yml"

- name: "Install Miniflux"
  ansible.builtin.include_tasks: "miniflux.yml"
