# https://github.com/ellite/Wallos?tab=readme-ov-file#docker-1
---

- name: "Prepare task variables"
  ansible.builtin.set_fact:
    wallos_service_id: "wallos"
    wallos_docker_settings: "{{ wallos_docker_settings_default | combine(wallos_docker_settings) }}"

- name: "Make sure config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"
    mode: "0750"
  loop:
    - "{{ wallos_install_dir }}/db"
    - "{{ wallos_install_dir }}/logos"

- name: "Make sure {{ wallos_docker_settings.network }} docker network exists"
  when: wallos_docker_settings.network != "host"
  community.general.docker_network:
    name: "{{ wallos_docker_settings.network }}"
    state: "present"

- name: "Run wallos container"
  community.general.docker_container:
    name: "{{ wallos_service_id }}"
    image: "bellamy/wallos:{{ wallos_version }}"
    networks:
      - name: "{{ wallos_docker_settings.network }}"
    state: "started"
    env: "{{ wallos_env_default | combine(wallos_env) }}"
    ports:
      - "{{ wallos_webui_port }}:80"
    volumes:
      - "{{ wallos_install_dir }}/db:/var/www/html/db"
      - "{{ wallos_install_dir }}/logos:/var/www/html/images/uploads/logos"
    restart_policy: "unless-stopped"
